# Generated by Django 5.0.2 on 2025-01-07 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_logo', models.ImageField(blank=True, upload_to='programs/images')),
            ],
        ),
        migrations.CreateModel(
            name='PostArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tittle', models.CharField(max_length=150)),
                ('caption', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('art_type', models.CharField(choices=[('2', '2D'), ('3', '3D')], default='2D', max_length=2)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_art.category')),
            ],
            options={
                'verbose_name': 'post portfolio',
                'verbose_name_plural': 'posts portfolio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='user/post/images')),
                ('acessibility_caption', models.CharField(max_length=120)),
                ('caption', models.CharField(max_length=240)),
                ('image_post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.postart')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('user_picture', models.ImageField(blank=True, upload_to='user/pictures')),
                ('profile_banner', models.ImageField(blank=True, upload_to='user/banners')),
                ('saved_posts', models.ManyToManyField(blank=True, to='post_art.postart')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='postart',
            name='post_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.profile'),
        ),
        migrations.AddField(
            model_name='postart',
            name='used_programs',
            field=models.ManyToManyField(to='post_art.usedprograms'),
        ),
    ]
