# Generated by Django 5.0.2 on 2025-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postart',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postart',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='post_art.postart'),
        ),
    ]
