# Generated by Django 5.0.2 on 2025-03-20 13:32

import post_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postart',
            name='post_thumb',
            field=models.ImageField(upload_to=post_art.models.thumb_upload_to),
        ),
    ]
