# Generated by Django 5.0.2 on 2025-01-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postart',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
