# Generated by Django 5.0.2 on 2025-03-01 20:30

import post_art.custom_model_fields
import post_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0002_postart_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='postart',
            name='youtube_link',
            field=post_art.custom_model_fields.YoutubeUrlField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post_img',
            field=models.ImageField(upload_to=post_art.models.post_images_upload_to),
        ),
    ]
