# Generated by Django 5.0.2 on 2025-03-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0002_alter_postart_post_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.profile')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.postart')),
            ],
        ),
    ]
