# Generated by Django 5.0.2 on 2025-03-01 21:08

import post_art.custom_model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0003_postart_youtube_link_alter_postimages_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='postart',
            name='marmoview',
            field=post_art.custom_model_fields.MarmosetFileField(blank=True, null=True, upload_to=''),
        ),
    ]
