# Generated by Django 5.0.2 on 2025-03-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postart',
            old_name='views',
            new_name='views_number',
        ),
    ]
