# Generated by Django 5.0.2 on 2025-03-24 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0004_rename_views_postart_views_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('like_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.profile')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_art.postart')),
            ],
        ),
    ]
