# Generated by Django 5.0.2 on 2025-03-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postart',
            name='likes',
        ),
    ]
