# Generated by Django 5.0.2 on 2025-03-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0006_remove_postart_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postart',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
