# Generated by Django 5.0.2 on 2025-03-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0007_postart_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_type', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post_art.profile')),
                ('programs_known', models.ManyToManyField(to='post_art.usedprograms')),
                ('hiring', models.ManyToManyField(to='post_art.skill')),
            ],
        ),
    ]
