# Generated by Django 5.0.2 on 2025-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0008_hiring_skill_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
