# Generated by Django 5.0.2 on 2025-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0009_about_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(to='post_art.skill'),
        ),
        migrations.AlterField(
            model_name='about',
            name='hiring',
            field=models.ManyToManyField(to='post_art.hiring'),
        ),
    ]
