# Generated by Django 5.0.2 on 2025-04-01 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0010_about_skills_alter_about_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
