# Generated by Django 4.2.30 on 2026-05-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0011_comments_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created', '-id']},
        ),
    ]
