# Generated by Django 4.2.30 on 2026-06-06 17:27

from django.db import migrations, models
import post_art.custom_model_fields
import post_art.models.post_art
import post_art.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0013_post_media_and_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postart',
            name='marmoview',
            field=post_art.custom_model_fields.MarmosetFileField(blank=True, null=True, upload_to=post_art.models.post_art.marmoview_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, upload_to=post_art.models.profile.profile_banner_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, upload_to=post_art.models.profile.profile_picture_upload_to),
        ),
    ]
