# Generated by Django 4.2.30 on 2026-07-09 13:23

from django.db import migrations, models
import django.db.models.deletion
import post_art.models.briefing_attachment
import post_art.models.chat_attachment
import post_art.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_art', '0021_follow_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name_snapshot', models.CharField(max_length=100)),
                ('tier_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=10)),
                ('requested_deadline', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'briefing',
                'verbose_name_plural': 'briefings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_deadline', models.DateField()),
                ('new_deadline', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='post_art.briefing')),
            ],
            options={
                'verbose_name': 'pedido de extensão de prazo',
                'verbose_name_plural': 'pedidos de extensão de prazo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_conversations', to='post_art.profile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_conversations', to='post_art.profile')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='post_art.commissiontier')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'unique_together': {('client', 'artist', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('briefing_sent', 'Briefing enviado'), ('briefing_response', 'Resposta ao briefing'), ('extension_request', 'Pedido de extensão de prazo'), ('extension_response', 'Resposta à extensão de prazo')], default='text', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='post_art.conversation')),
                ('related_briefing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='post_art.briefing')),
                ('related_extension_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='post_art.deliveryextensionrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='post_art.profile')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=post_art.models.chat_attachment.chat_attachment_upload_to, validators=[post_art.models.validators.validate_attachment_size])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='post_art.chatmessage')),
            ],
            options={
                'verbose_name': 'anexo de mensagem',
                'verbose_name_plural': 'anexos de mensagem',
            },
        ),
        migrations.CreateModel(
            name='BriefingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=post_art.models.briefing_attachment.briefing_attachment_upload_to, validators=[post_art.models.validators.validate_attachment_size])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='post_art.briefing')),
            ],
            options={
                'verbose_name': 'anexo de briefing',
                'verbose_name_plural': 'anexos de briefing',
            },
        ),
        migrations.AddField(
            model_name='briefing',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='post_art.conversation'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefings', to='post_art.commissiontier'),
        ),
    ]
